name: progress_border
description: A BoxBorder like Border but draw part of the border according to the progress, supported circle, rect, rectangle.
version: 0.0.4
homepage: https://github.com/shirne/progress_border

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '< 3.7.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

