name: progress_border
description: A BoxBorder like Border but draw part of the border according to the progress, supported circle, rect, rectangle.
version: 0.1.5
homepage: https://github.com/shirne/progress_border
screenshots: 
  - description: 'proggress border preview'
    path: preview/preview.gif
topics: 
  - border
  - progress

environment:
  sdk: '>=2.14.0 <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

